module.exports = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  CONFIG_MISSING: 'CONFIG_MISSING',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
